import type { Metadata } from 'next';
import localFont from 'next/font/local';
import BottomNav from '@/components/BottomNav';
import TopNav from '@/components/TopNav';
import 'react-tooltip/dist/react-tooltip.css';
import './globals.css';
import SideNav from '@/components/SideNav';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex sm:flex-col min-h-[100vh] antialiased`}
      >
        <TopNav />
        <SideNav />
        <main className="h-[--main-height] my-[--nav-height] md:w-4/5 md:ml-[20%] md:my-2">
          {children}
        </main>
        <BottomNav />
      </body>
    </html>
  );
}
